--
-- RagnarokOnline Settings File
-- Generated by RO OpenSetup, Version 2.18.0.578 ( http://ai4rei.net/p/opensetup )
--

-- Workaround for people with broken client folder
-- Note: The client removes this when it saves settings.
--
if OptionInfoList==nil then
	OptionInfoList = {}
end
if CmdOnOffList==nil then
	CmdOnOffList = {}
end
-- End of Workaround


-- Settings
--

OptionInfoList["Trilinear"] = 0
OptionInfoList["Bgm_Volume"] = 5
OptionInfoList["Effect_Volume"] = 5
OptionInfoList["MouseExclusive"] = 1
OptionInfoList["ISFULLSCREENMODE"] = 0
OptionInfoList["WIDTH"] = 1024
OptionInfoList["HEIGHT"] = 768
OptionInfoList["BITPERPIXEL"] = 32
OptionInfoList["DEVICECNT"] = 0
OptionInfoList["MODECNT"] = 0
OptionInfoList["SPRITEMODE"] = 2
OptionInfoList["TEXTUREMODE"] = 2
CmdOnOffList["/bgm"] = 0
CmdOnOffList["/sound"] = 0
CmdOnOffList["/notrade"] = 0
CmdOnOffList["/noshift"] = 0
CmdOnOffList["/noctrl"] = 1
CmdOnOffList["/skillfail"] = 1
CmdOnOffList["/notalkmsg"] = 0
CmdOnOffList["/notalkmsg2"] = 0
CmdOnOffList["/showname"] = 1
CmdOnOffList["/fog"] = 0
CmdOnOffList["/aura"] = 0
CmdOnOffList["/window"] = 0
CmdOnOffList["/miss"] = 1
CmdOnOffList["/effect"] = 1
CmdOnOffList["/shopping"] = 0
CmdOnOffList["/stateinfo"] = 1
CmdOnOffList["/loginout"] = 0
CmdOnOffList["/snap"] = 0
CmdOnOffList["/itemsnap"] = 0
CmdOnOffList["/skillsnap"] = 1
CmdOnOffList["/camera"] = 0
CmdOnOffList["/hoai"] = 0
CmdOnOffList["/merai"] = 0
CmdOnOffList["/lightmap"] = 0
CmdOnOffList["/monsterhp"] = 1
CmdOnOffList["/q1"] = 0
CmdOnOffList["/q2"] = 0
CmdOnOffList["/aura2"] = 0
CmdOnOffList["/btg"] = 1
CmdOnOffList["/cashshop"] = 1
CmdOnOffList["/goldpc"] = 1
CmdOnOffList["/roulette"] = 1
CmdOnOffList["/quake"] = 1
CmdOnOffList["/mable"] = 1
CmdOnOffList["/zoom"] = 0

-- Preserved client settings
--

OptionInfoList["ChangeChatMode"] = 1
OptionInfoList["Outdoor_ViewDistance"] = 689.39978
OptionInfoList["AutoOpen1to1Window"] = 1
OptionInfoList["bLockItemDropFromItemWnd"] = 0
OptionInfoList["ShowBattleFieldIcon"] = 1
OptionInfoList["Show_SkillDescript"] = 0
OptionInfoList["AutoOpen1to1Window_Friend"] = 1
OptionInfoList["Simplicity_SkillList"] = 0
OptionInfoList["Indoor_ViewLatitude"] = -45
OptionInfoList["LockMouse"] = 0
OptionInfoList["Window_YPos"] = 0
OptionInfoList["SkinName"] = "<Basic Skin>"
OptionInfoList["ChannelCopID"] = 0
OptionInfoList["Window_XPos"] = 0
OptionInfoList["Outdoor_ViewLatitude"] = -37
OptionInfoList["PlaySound_Open1to1Window"] = 1
OptionInfoList["Indoor_ViewDistance"] = 300
